### ISSUE TITLE
Support glob patterns

### ISSUE THREAD

**Issue by vgrigoruk** [peakon/s3-cache-buildkite-plugin#6]
This is not supported at the moment (`tar` doesn't support file pattens):
```
      - peakon/s3-cache#v2.1.2:
          save:
            - key: 'v1-node-modules-{{ checksum("yarn.lock") }}'
              paths: [ "packages/*/node_modules" ]

```
